[versions]
coroutine = "1.7.1"
androidCore = "1.8.0"
androidGradlePlugin = "8.0.2"
androidLifecycleRuntime = "2.3.1"
androidAppCompat = "1.5.0"
compose = "1.5.1"
composeMaterial = "1.3.1"
composeTooling = "1.5.0"
composeFoundation = "1.3.1"
composeNavigation = "2.5.3"
hilt = "2.47"
hiltNavigation = "1.0.0"
retrofit = "2.9.0"
okhttp = "4.11.0"
serialization = "1.5.0"
serialzationJson = "1.5.1"
serializationConverter = "1.0.0"
coil = "2.4.0"
room = "2.5.0"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidCore" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidLifecycleRuntime" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidAppCompat" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeFoundation" }
androidx-compose-preview = { module = "androidx.compose.ui:ui-tooling-preview-android", version.ref = "composeTooling" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
androidx-compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeTooling" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }

androidx-hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }

kotlin-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
kotlin-coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "serialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialzationJson" }
kotlin-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "serializationConverter" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }